[project]
name = "real-word-case-be"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "ollama>=0.5.1",
    "orjson>=3.11.0",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
